apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
  labels:
    app: capstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
      - name: capstone
        image: anoobhamza136/capstone:v1
        ports:
        - containerPort: 8080

--- 
apiVersion: v1
kind: Service
metadata:
  name: capstone-svc
spec:
  type: NodePort
  selector:
    app: capstone
  ports:
    - port: 80 # The port exposed by the Service within the cluster
      targetPort: 8080 # The port on which your application container listens inside the pod
      nodePort: 30000 # The static port exposed on each Node's IP address (range 30000-32767)